package com.rv.framework.cmd

object KeyCodeConst {
    const val MCU_KEY_NONE = 0; //无按键
    const val MCU_KEY_POWER =1; //关机键
    const val MCU_KEY_NEXT = 2; //下一曲或下一台
    const val MCU_KEY_PREV = 3; //上一曲或上一台
    const val MCU_KEY_PLAY = 4;
    const val MCU_KEY_STOP = 5;
    const val MCU_KEY_PLAYPAUSE = 6; //播放暂停
    const val MCU_KEY_FF = 7; //快进
    const val MCU_KEY_RF = 8; //快退
    const val MCU_KEY_MENU = 9; //主页
    const val MCU_KEY_DISP = 10;
    const val MCU_KEY_REP = 11;
    const val MCU_KEY_AMS = 12;
    const val MCU_KEY_APS = 13;
    const val MCU_KEY_BND = 14; //收音波段
    const val MCU_KEY_EJECT = 15;
    const val MCU_KEY_MODE = 16; //MODE
    const val MCU_KEY_MUTE = 17; //静音
    const val MCU_KEY_VOL_ADD = 18; //音量加
    const val MCU_KEY_VOL_SUB = 19; //音量减
    const val MCU_KEY_SETUP = 20; //设置
    const val MCU_KEY_BLACK = 21; //黑屏
    const val MCU_KEY_HANGUP = 22; //挂断
    const val MCU_KEY_TALK = 23; //接听
    const val MCU_KEY_LEFT = 24; //左或上一曲
    const val MCU_KEY_UP = 25; //上或上一曲
    const val MCU_KEY_DOWN = 26; //下或下一曲
    const val MCU_KEY_RIGHT = 27; //右或下一曲
    const val MCU_KEY_ENTER = 28; //播放暂停
    const val MCU_KEY_REPEAT = 29;
    const val MCU_KEY_RANDOM = 30;
    const val MCU_KEY_ANGLE = 31;
    const val MCU_KEY_DISPLAY = 32;
    const val MCU_KEY_SUBT = 33;
    const val MCU_KEY_SOUNDLANG = 34;
    const val MCU_KEY_ZOOM = 35;
    const val MCU_KEY_NUM0 = 36;
    const val MCU_KEY_NUM1 = 37;
    const val MCU_KEY_NUM2 = 38;
    const val MCU_KEY_NUM3 = 39;
    const val MCU_KEY_NUM4 = 40;
    const val MCU_KEY_NUM5 = 41;

    const val MCU_KEY_NUM6 = 42;
    const val MCU_KEY_NUM7 = 43;
    const val MCU_KEY_NUM8 = 44;
    const val MCU_KEY_NUM9 = 45;
    const val MCU_KEY_NUM10 = 46;
    const val MCU_KEY_GOTO = 47;
    const val MCU_KEY_LOCDX = 48;
    const val MCU_KEY_STMONO = 49;
    const val MCU_KEY_L_R = 50;
    const val MCU_KEY_EQ = 51;
    const val MCU_KEY_TITLE = 52;
    const val MCU_KEY_SLOW = 53;
    const val MCU_KEY_RADIO = 54;
    const val MCU_KEY_NAV = 55;
    const val MCU_KEY_DVD = 57;
    const val MCU_KEY_SEL = 58;
    const val MCU_KEY_BT = 59;
    const val MCU_KEY_NUM1_LONG = 64;
    const val MCU_KEY_NUM2_LONG = 65;
    const val MCU_KEY_NUM3_LONG = 66;
    const val MCU_KEY_NUM4_LONG = 67;
    const val MCU_KEY_NUM5_LONG = 68;
    const val MCU_KEY_NUM6_LONG = 69;
    const val MCU_KEY_CLOCK = 73;
    const val MCU_KEY_RETURN = 85;
    const val MCU_KEY_SEARCH = 87;
    const val MCU_KEY_DUAL = 88;
    const val MCU_KEY_TAB = 89;
    const val MCU_KEY_MAX_AC = 90;
    const val MCU_KEY_AC = 91;
    const val MCU_KEY_BLOW_FONT = 92;
    const val MCU_KEY_BLOW_REVERSE = 93;
    const val MCU_KEY_AUTO = 94;
    const val MCU_KEY_AIR_SW = 95;
    const val MCU_KEY_RIGHT_TEMP_ADD = 96;
    const val MCU_KEY_RIGHT_TEMP_SUB = 97;
    const val MCU_KEY_FAN_SUB = 98;
    const val MCU_KEY_FAN_ADD = 99;
    const val MCU_KEY_LEFT_TEMP_ADD = 100;

    const val MCU_KEY_LEFT_TEMP_SUB = 101;
    const val MCU_KEY_CAR_CAM = 102;
    const val MCU_KEY_AUX = 105;
    const val MCU_KEY_AIR_MODE = 106;
    const val MCU_KEY_PHONE_APP = 110;
    const val MCU_KEY_DVR = 111;
    const val MCU_KEY_RESOURCE_MANAGE = 112;
    const val MCU_KEY_TASK_LIST = 113;
    const val MCU_KEY_MIDDLE_CONTROL = 114; //原车中控
    const val MCU_KEY_CAR_MEDIA = 115;
    const val MCU_KEY_SHENGKONG = 116; //语音按键
    const val MCU_KEY_CAR_INDEX1 = 117;
    const val MCU_KEY_CAR_INDEX2 = 118;
    const val MCU_KEY_CAR_INDEX3 = 119;
    const val MCU_KEY_RIGHT_SIGH = 122;//右视
    const val MCU_KEY_LEFT_SIGH = 123;//左视
    const val MCU_KEY_FRONT_SIGH = 124;//前视
    const val MCU_KEY_BLOW_MODE = 128;//
    const val MCU_KEY_CAR_INDEX5 = 132;
    const val MCU_KEY_CAR_INDEX6 = 133;
    const val MCU_KEY_CAR_INDEX7 = 134;
    const val MCU_KEY_CAR_INDEX8 = 135;
    const val MCU_KEY_CARPLAY = 136;
    const val MCU_KEY_CAR_INDEX4 = 137;
    const val MCU_KEY_CAR_Gauges = 138;
    const val MCU_KEY_SPLIT_SCREEN = 139;
    const val MCU_KEY_PHONE_LICK = 140;
    const val MCU_KEY_PAUSE = 181;
    const val MCU_KEY_XING = 182;
    const val MCU_KEY_JING = 183;
    const val MCU_KEY_APPLIST = 184; //应用
    const val MCU_KEY_WAKE_UP = 199;
    const val MCU_KEY_RADIO_FM = 208;
    const val MCU_KEY_RADIO_AM = 209;
    const val MCU_KEY_PIP = 240;
    const val MCU_KEY_BEEP = 241;
    const val MCU_KEY_MUSIC = 242; //音乐
    const val MCU_KEY_MOVIE = 243; //视频或电影

    const val MCU_KEY_NP = 244;
    const val MCU_KEY_TOUCH_CAL = 245;
    const val MCU_KEY_BACKLIGHT_SUB = 246;
    const val MCU_KEY_STANDBY = 247;
    const val MCU_KEY_BACK_CAM = 250;//一键进入 360 全景
}